workflows:
  android-release:
    name: Android Release (Signed)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      android: latest
      groups:
        - keystore_credentials
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Recreate android folder (if missing)
        script: flutter create .
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your@email.com
